# Generated by Django 2.2.7 on 2019-12-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_worker_total_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('work_desc', models.TextField()),
                ('charge', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
                ('modified_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserProfile')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Worker')),
            ],
        ),
    ]
