# Generated by Django 2.2.7 on 2019-12-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_worker_total_money'),
        ('WorkOrder', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=20)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrder.Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserProfile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Worker')),
            ],
        ),
    ]
