# Generated by Django 2.2.6 on 2019-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60)),
                ('basic_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('work', models.ManyToManyField(to='Home.Work')),
            ],
        ),
    ]
