# Generated by Django 2.2.6 on 2019-11-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
    ]
