# Generated by Django 2.2.6 on 2019-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
